# import libraries
import logging
import unittest
from unittest import TestCase
# import ogd libraries.
from ogd.common.configs.TestConfig import TestConfig
from ogd.common.utils.Logger import Logger
from ogd.common.schemas.tables.EventMapSchema import EventMapSchema
from ogd.common.schemas.tables.ColumnSchema import ColumnSchema
# import locals
from src.ogd.common.schemas.tables.EventTableSchema import EventTableSchema
from tests.config.t_config import settings

def setUpModule():
    _testing_cfg = TestConfig.FromDict(name="SchemaTestConfig", unparsed_elements=settings)
    _level       = logging.DEBUG if _testing_cfg.Verbose else logging.INFO
    Logger.std_logger.setLevel(_level)

class EmptyCase(TestCase):
    """EventTableSchema test case where no initialization is used at class level.

    Fixture:
    * No initialization of a `EventTableSchema` object

    Case Categories:
    * Loading functions.
        * Appropriate here since the fixture doesn't set up an object.
    * Parsing functions. 
        * We test these so as to get details of where loading fails.
    """

    def test_FromDict(self):
        """Test case for whether the FromDict function is working properly.
        """
        dict = {
            "column_map" : {
                "session_id"           : "session_id",
                "app_id"               : "app_id",
                "timestamp"            : "timestamp",
                "event_name"           : "event_name",
                "event_data"           : "event_data",
                "event_source"         : "event_source",
                "app_version"          : "app_version",
                "app_branch"           : "app_branch",
                "log_version"          : "log_version",
                "time_offset"          : "offset",
                "user_id"              : "user_id",
                "user_data"            : "user_data",
                "game_state"           : "game_state",
                "event_sequence_index" : "index"
            },
            "columns" : [
                {
                    "name": "session_id",
                    "readable": "Session ID",
                    "description": "Unique identifier for the gameplay session",
                    "type": "str"
                },
                {
                    "name": "app_id",
                    "readable": "App Name",
                    "description": "A string identifying which game from which the event came",
                    "type": "str"
                },
                {
                    "name": "timestamp",
                    "readable": "Timestamp",
                    "description": "The time when the event was logged",
                    "type": "datetime"
                },
                {
                    "name": "event_name",
                    "readable": "Event Type",
                    "description": "The type of event logged",
                    "type": "str"
                },
                {
                    "name": "event_data",
                    "readable": "Event Data",
                    "description": "Data specific to an event type, encoded as a JSON string",
                    "type": "json"
                },
                {
                    "name": "event_source",
                    "readable": "Event Source",
                    "description": "An enum member indicating whether the event was generated by the Game, or by a Detector",
                    "type": "enum('GAME', 'GENERATED')"
                },
                {
                    "name": "app_version",
                    "readable": "App Version",
                    "description": "The version of the game from which the event came",
                    "type": "str"
                },
                {
                    "name": "app_branch",
                    "readable": "App Branch",
                    "description": "The branch of the game from which the event came",
                    "type": "str"
                },
                {
                    "name": "log_version",
                    "readable": "Log Version",
                    "description": "The version of the logging code for the game from which the event came",
                    "type": "str"
                },
                {
                    "name": "offset",
                    "readable": "Time Offset",
                    "description": "The local offset of the event time from GMT",
                    "type": "timezone"
                },
                {
                    "name": "user_id",
                    "readable": "Player ID",
                    "description": "A custom, per-player ID, only exists if player entered an ID on one of our custom portal pages, else null",
                    "type": "str"
                },
                {
                    "name": "user_data",
                    "readable": "User Data",
                    "description": "Metadata specific to a user, encoded as a JSON string",
                    "type": "json"
                },
                {
                    "name": "game_state",
                    "readable": "Game State",
                    "description": "Metadata about the state of the game when the event occurred, encoded as a JSON string",
                    "type": "json"
                },
                {
                    "name": "index",
                    "readable": "Event-Sequence Index",
                    "description": "Counter of events in the session, from 0. A row with session_n = i is the (i+1)-th event of the session",
                    "type": "int"
                }
            ]
        }
        schema = EventTableSchema.FromDict(name="EventTableSchema", unparsed_elements=dict)
        col_map = EventMapSchema(
            name                 = "CorrectEventMap",
            session_id           = "session_id",
            app_id               = "app_id",
            timestamp            = "timestamp",
            event_name           = "event_name",
            event_data           = "event_data",
            event_source         = "event_source",
            app_version          = "app_version",
            app_branch           = "app_branch",
            log_version          = "log_version",
            time_offset          = "offset",
            user_id              = "user_id",
            user_data            = "user_data",
            game_state           = "game_state",
            event_sequence_index = "index"
        )
        cols = [
            ColumnSchema(
                name        = "session_id",
                readable    = "Session ID",
                description = "Unique identifier for the gameplay session",
                value_type  = "str"
            ),
            ColumnSchema(
                name        = "app_id",
                readable    = "App Name",
                description = "A string identifying which game from which the event came",
                value_type  = "str"
            ),
            ColumnSchema(
                name = "timestamp",
                readable = "Timestamp",
                description = "The time when the event was logged",
                value_type = "datetime"
            ),
            ColumnSchema(
                name = "event_name",
                readable = "Event Type",
                description = "The type of event logged",
                value_type = "str"
            ),
            ColumnSchema(
                name = "event_data",
                readable = "Event Data",
                description = "Data specific to an event type, encoded as a JSON string",
                value_type = "json"
            ),
            ColumnSchema(
                name = "event_source",
                readable = "Event Source",
                description = "An enum member indicating whether the event was generated by the Game, or by a Detector",
                value_type = "enum('GAME', 'GENERATED')"
            ),
            ColumnSchema(
                name = "app_version",
                readable = "App Version",
                description = "The version of the game from which the event came",
                value_type = "str"
            ),
            ColumnSchema(
                name = "app_branch",
                readable = "App Branch",
                description = "The branch of the game from which the event came",
                value_type = "str"
            ),
            ColumnSchema(
                name = "log_version",
                readable = "Log Version",
                description = "The version of the logging code for the game from which the event came",
                value_type = "str"
            ),
            ColumnSchema(
                name = "offset",
                readable = "Time Offset",
                description = "The local offset of the event time from GMT",
                value_type = "timezone"
            ),
            ColumnSchema(
                name = "user_id",
                readable = "Player ID",
                description = "A custom, per-player ID, only exists if player entered an ID on one of our custom portal pages, else null",
                value_type = "str"
            ),
            ColumnSchema(
                name = "user_data",
                readable = "User Data",
                description = "Metadata specific to a user, encoded as a JSON string",
                value_type = "json"
            ),
            ColumnSchema(
                name = "game_state",
                readable = "Game State",
                description = "Metadata about the state of the game when the event occurred, encoded as a JSON string",
                value_type = "json"
            ),
            ColumnSchema(
                name = "index",
                readable = "Event-Sequence Index",
                description = "Counter of events in the session, from 0. A row with session_n = i is the (i+1)-th event of the session",
                value_type = "int"
            )
        ]

        self.assertIsInstance(schema.Name, str)
        self.assertEqual(schema.Name, "EventTableSchema")
        self.assertIsInstance(schema.ColumnMap, EventMapSchema)
        self.assertEqual(schema.ColumnMap, col_map)
        self.assertIsInstance(schema.Columns, list)
        self.assertEqual(schema.Columns, cols)

    def test_FromFile_preset(self):
        col_map = EventMapSchema(
            name                 = "CorrectEventMap",
            session_id           = "session_id",
            app_id               = "app_id",
            timestamp            = "timestamp",
            event_name           = "event_name",
            event_data           = "event_data",
            event_source         = "event_source",
            app_version          = "app_version",
            app_branch           = "app_branch",
            log_version          = "log_version",
            time_offset          = "offset",
            user_id              = "user_id",
            user_data            = "user_data",
            game_state           = "game_state",
            event_sequence_index = "index"
        )
        cols = [
            ColumnSchema(
                name        = "session_id",
                readable    = "Session ID",
                description = "Unique identifier for the gameplay session",
                value_type  = "str"
            ),
            ColumnSchema(
                name        = "app_id",
                readable    = "App Name",
                description = "A string identifying which game from which the event came",
                value_type  = "str"
            ),
            ColumnSchema(
                name = "timestamp",
                readable = "Timestamp",
                description = "The time when the event was logged",
                value_type = "datetime"
            ),
            ColumnSchema(
                name = "event_name",
                readable = "Event Type",
                description = "The type of event logged",
                value_type = "str"
            ),
            ColumnSchema(
                name = "event_data",
                readable = "Event Data",
                description = "Data specific to an event type, encoded as a JSON string",
                value_type = "json"
            ),
            ColumnSchema(
                name = "event_source",
                readable = "Event Source",
                description = "An enum member indicating whether the event was generated by the Game, or by a Detector",
                value_type = "enum('GAME', 'GENERATED')"
            ),
            ColumnSchema(
                name = "app_version",
                readable = "App Version",
                description = "The version of the game from which the event came",
                value_type = "str"
            ),
            ColumnSchema(
                name = "app_branch",
                readable = "App Branch",
                description = "The branch of the game from which the event came",
                value_type = "str"
            ),
            ColumnSchema(
                name = "log_version",
                readable = "Log Version",
                description = "The version of the logging code for the game from which the event came",
                value_type = "str"
            ),
            ColumnSchema(
                name = "offset",
                readable = "Time Offset",
                description = "The local offset of the event time from GMT",
                value_type = "timezone"
            ),
            ColumnSchema(
                name = "user_id",
                readable = "Player ID",
                description = "A custom, per-player ID, only exists if player entered an ID on one of our custom portal pages, else null",
                value_type = "str"
            ),
            ColumnSchema(
                name = "user_data",
                readable = "User Data",
                description = "Metadata specific to a user, encoded as a JSON string",
                value_type = "json"
            ),
            ColumnSchema(
                name = "game_state",
                readable = "Game State",
                description = "Metadata about the state of the game when the event occurred, encoded as a JSON string",
                value_type = "json"
            ),
            ColumnSchema(
                name = "index",
                readable = "Event-Sequence Index",
                description = "Counter of events in the session, from 0. A row with session_n = i is the (i+1)-th event of the session",
                value_type = "int"
            )
        ]
        # try to load from default location
        schema = EventTableSchema.FromFile(file_name="OGD_EVENT_FILE", directory=EventTableSchema._DEFAULT_SCHEMA_PATH)
        self.assertIsInstance(schema, EventTableSchema)
        self.assertIsInstance(schema.Name, str)
        self.assertIsInstance(schema.ColumnMap, EventMapSchema)
        self.assertEqual(schema.Name, "OGD_EVENT_FILE")
        self.assertEqual(schema.ColumnMap, col_map)
        self.assertIsInstance(schema.Columns, list)
        self.assertEqual(schema.Columns, cols)
