# Workflow to build and test the APIUtils project
name: CI Script - OGD Common
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/CI_common.yml'
    - '.github/workflows/BUILD_common.yml'
    - '.github/actions/**'
    - 'pyproject.toml'
    - 'requirements.txt'
    - 'src/**'

jobs:

  build:
    name: Build Python Package
    uses: ./.github/workflows/BUILD_common.yml
    with:
      with_caching: false
