# Workflow to build and test the APIUtils project
name: CI Script - OGD Common
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/CI_common.yml'
    - '.github/workflows/BUILD_common.yml'
    - '.github/actions/**'
    - 'pyproject.toml'
    - 'requirements.txt'
    - 'src/**'

jobs:

  build:
    name: Build Python Package
    uses: ./.github/workflows/BUILD_common.yml
    with:
      with_caching: false

  # Run testbeds in configs module

  testbed_configs:
    name: Config Testbeds
    needs: build
    uses: ./.github/workflows/TEST_Configs.yml

  # Run testbeds in models module

  testbed_models:
    name: Models Testbed
    needs: build
    uses: ./.github/workflows/TEST_Models.yml

  # Run testbeds in schemas module

  testbed_schema:
    name: Schema base class Testbed
    needs: build
    uses: ./.github/workflows/TEST_schemas_Schema.yml

  testbed_game_schemas:
    name: Game Schema Testbeds
    needs: build
    uses: ./.github/workflows/TEST_schemas_EventSchemas.yml

  # Run testbeds in storage module

  testbed_connectors:
    name: Connector Testbeds
    needs: build
    uses: ./.github/workflows/TEST_storage_Connectors.yml

  testbed_interfaces:
    name: Interface Testbeds
    needs: build
    uses: ./.github/workflows/TEST_storage_Interfaces.yml

  # Run testbeds in utils module

  testbed_fileio:
    name: FileIO Testbed
    needs: build
    uses: ./.github/workflows/TEST_utils_FileIO.yml

  testbed_typing:
    name: "`typing` Testbed"
    needs: build
    uses: ./.github/workflows/TEST_utils_typing.yml
