# Workflow to build and deploy a new release of ogd-common to PyPi.
name: Release Script - OGD Common
on:
  release:
    types: [prereleased, released]
  workflow_dispatch: # Allow manual trigger of this workflow from the Actions tab

jobs:
  build:
    name: Build Python Package
    uses: ./.github/workflows/BUILD_common.yml
    with:
      with_caching: true

  # Run testbeds in configs module

  testbed_configs:
    name: Config Testbeds
    needs: build
    uses: ./.github/workflows/TEST_Configs.yml

  testbed_location_configs:
    name: Location Config Testbeds
    needs: build
    uses: ./.github/workflows/TEST_configs_LocationConfigs.yml

  testbed_storage_configs:
    name: Storage Config Testbeds
    needs: build
    uses: ./.github/workflows/TEST_configs_StorageConfigs.yml

  # Run testbeds in models module

  testbed_models:
    name: Models Testbed
    needs: build
    uses: ./.github/workflows/TEST_Models.yml

  # Run testbeds in schemas module

  testbed_schema:
    name: Schema base class Testbed
    needs: build
    uses: ./.github/workflows/TEST_schemas_Schema.yml

  testbed_game_schemas:
    name: Game Schema Testbeds
    needs: build
    uses: ./.github/workflows/TEST_schemas_EventSchemas.yml

  # Run testbeds in storage module

  testbed_connectors:
    name: Connector Testbeds
    needs: build
    uses: ./.github/workflows/TEST_storage_Connectors.yml
    secrets: inherit

  testbed_interfaces:
    name: Interface Testbeds
    needs: build
    uses: ./.github/workflows/TEST_storage_Interfaces.yml
    secrets: inherit

  # Run testbeds in utils module

  testbed_fileio:
    name: FileIO Testbed
    needs: build
    uses: ./.github/workflows/TEST_utils_FileIO.yml

  testbed_typing:
    name: "`typing` Testbed"
    needs: build
    uses: ./.github/workflows/TEST_utils_typing.yml

  release:
    name: Publish Release to PyPI
    needs: [build, testbed_schema]
    if: github.event.action == 'released'
    runs-on: ubuntu-22.04
    environment:
      name: pypi_release
      url: https://pypi.org/manage/project/opengamedata-common/
    permissions:
      id-token: write
    steps:
    - name: Restore Cached Build
      id: cached-build
      uses: actions/cache/restore@v4
      with:
        key: opengamedata-common-build-${{ github.run_id }}-${{ github.run_attempt }}
        path: ./dist/
        fail-on-cache-miss: true
    - name: Fail if Cache Restore Failed
      if: steps.cached-build.outputs.cache-hit == 'false'
      run: exit 1
    - name: Publish to PyPI
      if: steps.cached-build.outputs.cache-hit == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true

  pypi_beta:
    name: Publish Beta/RC to PyPI
    needs: [build, testbed_schema]
    if: github.event.action == 'prereleased' && !contains(github.ref_name, 'alpha')
    runs-on: ubuntu-22.04
    environment:
      name: pypi_release
      url: https://pypi.org/manage/project/opengamedata-common/
    permissions:
      id-token: write
    steps:
    - name: Restore Cached Build
      id: cached-build
      uses: actions/cache/restore@v4
      with:
        key: opengamedata-common-build-${{ github.run_id }}-${{ github.run_attempt }}
        path: ./dist/
        fail-on-cache-miss: true
    - name: Fail if Cache Restore Failed
      if: steps.cached-build.outputs.cache-hit == 'false'
      run: exit 1
    - name: Publish to PyPI
      if: steps.cached-build.outputs.cache-hit == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true

  prerelease:
    name: Publish Prerelease to PyPI
    needs: build
    if: github.event.action == 'prereleased' && contains(github.ref_name, 'alpha')
    runs-on: ubuntu-22.04
    environment:
      name: pypi_prerelease
      url: https://pypi.org/manage/project/opengamedata-common/
    permissions:
      id-token: write
    steps:
    - name: Restore Cached Build
      id: cached-build
      uses: actions/cache/restore@v4
      with:
        key: opengamedata-common-build-${{ github.run_id }}-${{ github.run_attempt }}
        path: ./dist/
        fail-on-cache-miss: true
    - name: Fail if Cache Restore Failed
      if: steps.cached-build.outputs.cache-hit == 'false'
      run: exit 1
    - name: Publish to PyPI Test
      if: steps.cached-build.outputs.cache-hit == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true
        repository-url: https://test.pypi.org/legacy/