# Workflow to test the DatasetKey class from the `utils` module
name: Testbed - Models
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
    - '.github/workflows/TEST_Models.yml'
    - '.github/actions/test_config/**'
    - 'tests/cases/models/config/*.py'
    - 'tests/config/**'
    - 'requirements.txt'

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}-Models
  cancel-in-progress: true

jobs:

  run_testbeds:
    name: Run Models Testbeds
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        testbed: [
          test_DatasetKey,
          test_Event,
          test_EventSet,
          test_Feature,
          test_SemanticVersion,
        ]
      fail-fast: false # we don't want to cancel just because one testbed fails.
      max-parallel: 20

    steps:
  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get Dependencies
      uses: opengamedata/setup-ogd-py-dependencies@v1.2
      with:
        python_version: ${{ vars.OGD_PYTHON_VERSION }}
    - name: Local self-install
      run: python -m pip install -e .
    - name: Set up Config File
      uses: ./.github/actions/test_config
      with:
          verbose_output: "True"
          with_schemas: "True"

  # 2. Build & configure remote environments

  # 3. Perform work
    - name: Execute ${{ matrix.testbed }} Testbed
      uses: opengamedata/actions-execute-testbed@v1.0
      with:
        directory: "tests/cases/models"
        test_file: "${{ matrix.testbed }}.py"
        python_version: ${{ vars.OGD_PYTHON_VERSION }}

  # 4. Cleanup & complete
